export enum PostulationEnum {
  PRESIDENTIAL = 'presidential',
  CONGRESSIONAL = 'congressional',
  PARLIAMENTARY = 'parliamentary',
  SENATOR = 'senator',
  GOVERNMENT = 'government',
  MUNICIPAL = 'municipal',
}

export enum PositionOrderEnum {
  PRESIDENTIAL = "PRESIDENTE DE LA REPÚBLICA",
  FIRST_VICE_PRESIDENT = "PRIMER VICEPRESIDENTE DE LA REPÚBLICA",
  SECOND_VICE_PRESIDENT = "SEGUNDO VICEPRESIDENTE DE LA REPÚBLICA",
  CONGRESSIONAL = "CONGRESISTA DE LA REPÚBLICA",
  PARLIAMENTARY = "REPRESENTANTE ANTE EL PARLAMENTO ANDINO"
}